name: Release

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: "Run semantic release"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}